// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package diwire

import (
	"github.com/Napat/pfd-api/app/internal/pfdserv/config"
	"github.com/Napat/pfd-api/app/internal/pfdserv/router"
)

// Injectors from wire.go:

func InitializeHttpServer(cfg *config.Config) *router.HttpServer {
	beefListAdaptor := NewBeefListAdaptor(cfg)
	beefService := NewBeefService(beefListAdaptor)
	httpHandler := NewHttpHandler(beefService)
	httpServer := NewHttpServer(httpHandler)
	return httpServer
}
